### PR TITLE
Remove enum34 from requirements

### LINKED ISSUE #63: Fails with python 3.6
Fails when attempting to build with python 3.6:
```
Collecting enum34==1.1.2 (from -r requirements.txt (line 3))
  Using cached enum34-1.1.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/Users/jgregory/.virtualenvs/sdx-decrypt/lib/python3.6/site-packages/setuptools/__init__.py", line 5, in <module>
        import distutils.core
      File "/Users/jgregory/.virtualenvs/sdx-decrypt/lib/python3.6/distutils/__init__.py", line 4, in <module>
        import imp
      File "/Users/jgregory/.virtualenvs/sdx-decrypt/lib/python3.6/imp.py", line 27, in <module>
        import tokenize
      File "/Users/jgregory/.virtualenvs/sdx-decrypt/lib/python3.6/tokenize.py", line 33, in <module>
        import re
      File "/Users/jgregory/.virtualenvs/sdx-decrypt/lib/python3.6/re.py", line 142, in <module>
        class RegexFlag(enum.IntFlag):
    AttributeError: module 'enum' has no attribute 'IntFlag'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/3x/cbmnscz143q40msktt0r68cr0000gn/T/pip-build-pi000xiz/enum34/
make: *** [build] Error 1
```

### PR DESCRIPTION
**Pull request by JamesGardiner**
## What? and Why?
This pull request removes the enum34 requirement from requirements.txt, which was causing travis python 3.6 builds to fail. Enum libraries shouldn't be specified in the requirements.txt file, as they are version dependent. It looks like the requirements.txt file was generated by doing `pip freeze > requirements.txt`, without thinking about possible issues. Closes #63.

## Checklist
  - [x] CHANGELOG.md updated? (if required)

### CODE REVIEW

**Comment by JamesGardiner** [comment]
[sdx-decypt fails to build with python 3.6 (1)](https://trello.com/c/eRYyavYM/214-sdx-decypt-fails-to-build-with-python-36-1)
